---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-service
 labels:
   serviceType: user-service
spec:
 selector:
  matchLabels:
   serviceType: user-service
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       serviceType: user-service
   spec:
     containers:
     - image: localhost:32000/rwibawa/user-service:1.1
       name: user-service
       env:
       - name: JAVA_OPTS
         value: -Xmx64m -Xms64m
       livenessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 40
         timeoutSeconds: 1
         periodSeconds: 15
       readinessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 40
         timeoutSeconds: 1
         periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
 name: user-service
spec:
 ports:
   - port: 8080
 selector:
   serviceType: user-service
 clusterIP: None
